# Generated by Django 6.0.5 on 2026-06-02 09:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/operators/', verbose_name='آواتار')),
                ('role', models.CharField(choices=[('operator', 'اپراتور عادی'), ('owner', 'صاحب سایت'), ('admin', 'مدیر')], default='operator', max_length=20, verbose_name='نقش')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='لیست تخصص\u200cهای اپراتور: ["چاپ", "تایپ", "طراحی"]', verbose_name='تخصص\u200cها')),
                ('rating', models.FloatField(default=0, verbose_name='امتیاز')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('completed_jobs', models.IntegerField(default=0, verbose_name='کارهای تکمیل شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='آماده به کار')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('wallet_balance', models.BigIntegerField(default=0, verbose_name='اعتبار کیف پول (تومان)')),
                ('total_earned', models.BigIntegerField(default=0, verbose_name='کل درآمد (تومان)')),
                ('pending_payment', models.BigIntegerField(default=0, verbose_name='در انتظار پرداخت (تومان)')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
                'db_table': 'operators',
                'indexes': [models.Index(fields=['phone'], name='operators_phone_972791_idx'), models.Index(fields=['role'], name='operators_role_91a933_idx'), models.Index(fields=['is_available'], name='operators_is_avai_eb4202_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(max_length=12, unique=True, verbose_name='کد پیگیری')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات خدمت')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='توضیحات مشتری')),
                ('operator_note', models.TextField(blank=True, null=True, verbose_name='یادداشت اپراتور')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پذیرش'), ('accepted', 'پذیرفته شده'), ('in_progress', 'در حال انجام'), ('completed', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('discount_amount', models.BigIntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('final_price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت نهایی (تومان)')),
                ('commission_percent', models.FloatField(default=20.0, verbose_name='درصد کمیسیون')),
                ('commission_amount', models.BigIntegerField(default=0, verbose_name='مبلغ کمیسیون (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/', verbose_name='فایل نتیجه')),
                ('result_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فایل نتیجه')),
                ('result_file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم فایل نتیجه (بایت)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت تحویل')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='امتیاز مشتری (۱ تا ۵)')),
                ('review', models.TextField(blank=True, null=True, verbose_name='نظر مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='home_module.operator', verbose_name='اپراتور')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('transaction_type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('payment', 'پرداخت خدمت'), ('commission', 'کمیسیون سایت'), ('operator_pay', 'پرداخت به اپراتور'), ('refund', 'بازگشت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('ref_code', models.CharField(max_length=100, unique=True, verbose_name='کد پیگیری')),
                ('is_successful', models.BooleanField(default=True, verbose_name='موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='home_module.operator', verbose_name='اپراتور')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='home_module.service', verbose_name='خدمت مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tracking_code'], name='services_trackin_f5e434_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='services_status_6676e7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['customer', 'status'], name='services_custome_308303_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['operator', 'status'], name='services_operato_b005e4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='services_created_22da02_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'created_at'], name='transaction_custome_fb8ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['operator', 'created_at'], name='transaction_operato_3b1727_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
    ]
