# Generated by Django 6.0.5 on 2026-06-12 16:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='commission_percent',
            field=models.FloatField(default=40.0, verbose_name='درصد کمیسیون'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خبر')),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='خلاصه')),
                ('icon', models.CharField(default='📰', max_length=10, verbose_name='آیکون')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'db_table': 'news',
                'ordering': ['-is_pinned', '-publish_date', 'order'],
                'indexes': [models.Index(fields=['is_active', 'publish_date'], name='news_is_acti_011d6d_idx'), models.Index(fields=['is_pinned'], name='news_is_pinn_ecedce_idx')],
            },
        ),
    ]
