# Generated by Django 6.0.5 on 2026-06-02 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(default='📋', max_length=50, verbose_name='آیکون (اموجی)')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('price', models.BigIntegerField(default=0, help_text='اگر قیمت ۰ باشد، "تماس بگیرید" نمایش داده می\u200cشود', verbose_name='قیمت (تومان) - ۰ یعنی تماس بگیرید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'خدمت صفحه اصلی',
                'verbose_name_plural': 'خدمات صفحه اصلی',
                'db_table': 'home_services',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
