# Generated by Django 6.0.5 on 2026-06-15 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_service_commission_percent_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='چت جدید', max_length=255, verbose_name='عنوان چت')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='مدل هوش مصنوعی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('total_messages', models.IntegerField(default=0, verbose_name='تعداد پیام\u200cها')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='کل توکن\u200cهای مصرفی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'جلسه چت هوشمند',
                'verbose_name_plural': 'جلسات چت هوشمند',
                'db_table': 'ai_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('system', 'سیستم')], max_length=10, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='توکن مصرفی')),
                ('cost', models.FloatField(default=0, verbose_name='هزینه (دلار)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home_module.chatsession', verbose_name='جلسه چت')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
