# Generated by Django 6.0.5 on 2026-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد صفحات'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_page',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت هر صفحه'),
        ),
    ]
