# Generated by Django 6.0.5 on 2026-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_service_page_count_service_price_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_page',
        ),
        migrations.AddField(
            model_name='homeservice',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد صفحات/اسلایدها'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='price_per_page',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت هر صفحه/اسلاید'),
        ),
    ]
