# Generated by Django 6.0.5 on 2026-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0006_alter_homeservice_page_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='page_count',
        ),
        migrations.AddField(
            model_name='service',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد صفحات/اسلایدها'),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='price_per_page',
            field=models.BooleanField(default=False, verbose_name='قیمت هر صفحه / اسلاید'),
        ),
    ]
