# Generated by Django 6.0.5 on 2026-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0007_remove_homeservice_page_count_service_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='این قیمت برای هر صفحه / اسلاید است.'),
        ),
    ]
