# Generated by Django 6.0.5 on 2026-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0008_alter_service_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservice',
            name='price_per_page',
            field=models.BooleanField(default=False, verbose_name='این قیمت برای هر صفحه / اسلاید است.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد صفحات/اسلایدها'),
        ),
    ]
