# Generated by Django 6.0.5 on 2026-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0009_alter_homeservice_price_per_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='price_per_page',
        ),
        migrations.AddField(
            model_name='homeservice',
            name='is_price_per_page',
            field=models.BooleanField(default=False, verbose_name=' قیمت به ازای هر صفحه/اسلاید است.'),
        ),
    ]
