# Generated by Django 6.0.5 on 2026-06-02 09:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'این نام کاربری قبلاً ثبت شده است.'}, max_length=150, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(error_messages={'unique': 'این شماره تلفن قبلاً ثبت شده است.'}, max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/customers/', verbose_name='آواتار')),
                ('wallet_balance', models.BigIntegerField(default=0, verbose_name='اعتبار کیف پول (تومان)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='گروه\u200cهایی که این کاربر عضو آن است.', related_name='customer_set', related_query_name='customer', to='auth.group', verbose_name='گروه\u200cها')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='دسترسی\u200cهای خاص برای این کاربر.', related_name='customer_set', related_query_name='customer', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'db_table': 'customers',
                'indexes': [models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['username'], name='customers_usernam_fad06d_idx')],
            },
        ),
    ]
