# Generated by Django 6.0.5 on 2026-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام کاربری قبلاً استفاده شده است.'}, max_length=150, unique=True, verbose_name='نام کاربری'),
        ),
    ]
